services:
  - type: web
    name: resume-ocr-api
    env: python
    pythonVersion: 3.11.9
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: gunicorn main:app
